### ISSUE TITLE
Не работает переключение на предыдущий режим одной кномпкой

### ISSUE THREAD

**Issue by re3lex** [AlexGyver/ChristmasLights#1]
При  управлении одной кнопкой и установленном массиве режимов `MY_MODE` переключение <Назад> путем тройного клика по кнопке не работает если индекс текущего режима больше нуля.
Это происходит потому, что [вот в этом блоке IF](https://github.com/AlexGyver/ChristmasLights/blob/master/firmware/notamesh4_gyver/1main.ino#L303) индекс режима `tek_my_mode` не уменьшается при клике на кнопку, если `tek_my_mode > 0`

Фикс:
```
if (tek_my_mode <= 0) 
  tek_my_mode = my_mode_count - 1;
else 
  tek_my_mode = tek_my_mode - 1;
```

**Comment by AlexGyver** [comment]
починил, спасибо
