### ISSUE TITLE
Поддержка NodeMCU

### ISSUE THREAD

**Issue by Akay7** [AlexGyver/ChristmasLights#3]
Хотелось бы видеть поддержку NodeMCU и других esp8266 плат.

**Comment by AlexGyver** [comment]
Не думаю что это возможно, код собран из всяких костыльных примеров и глупый компилятор есп его не вывезет)

**Comment by Akay7** [comment]
Нашёл не плохой проект для esp8266 https://github.com/Aircoookie/WLED
