### ISSUE TITLE
Работа на WEMOS D1 mini

### ISSUE THREAD

**Issue by Rodov** [AlexGyver/ChristmasLights#4]
Компиляция на WEMOS D1 mini вызывает проблемы, а с активированным пультом вообще не хочет компилироваться.

**Comment by AlexGyver** [comment]
Проект написан под avr arduino и под esp нужно переписывать

**Comment by Rodov** [comment]
Поскольку я не силен в программировании на Ардуино, то приходится только ждать, пока кто-нибудь пересоберет проект под WEMOS D1 mini

**Comment by AlexGyver** [comment]
Это точно

**Comment by Rodov** [comment]
Новостей нет? Никто не переписывал под ESP?

**Comment by AlexGyver** [comment]
> Новостей нет? Никто не переписывал под ESP?

Ищи на форуме, наверное есть
