### ISSUE TITLE
Не компилируется в Arduino IDE 1.8.15

### ISSUE THREAD

**Issue by simik-ru** [AlexGyver/ChristmasLights#5]
Новую версию сбивают с толку маркеры порядка байт в начале файлов, из-за этого она не видит макрос `#ifndef` в самом начале файла, и как результат ругается на закрывающий `#endif` без пары.
```
Arduino: 1.8.15 (Windows 10), Плата:"Arduino Nano, ATmega328P"


In file included from C:\Users\simik\Downloads\ChristmasLights-master\firmware\notamesh4_gyver_v1.1\1main.ino:162:0:
rainbow_beat.h:14:2: error: #endif without #if
 #endif
  ^~~~~
In file included from C:\Users\simik\Downloads\ChristmasLights-master\firmware\notamesh4_gyver_v1.1\1main.ino:166:0:
blendwave.h:29:2: error: #endif without #if
 #endif
  ^~~~~
In file included from C:\Users\simik\Downloads\ChristmasLights-master\firmware\notamesh4_gyver_v1.1\1main.ino:167:0:
fire.h:57:2: error: #endif without #if
 #endif
  ^~~~~
In file included from C:\Users\simik\Downloads\ChristmasLights-master\firmware\notamesh4_gyver_v1.1\1main.ino:168:0:
candles.h:27:2: error: #endif without #if
 #endif
  ^~~~~
In file included from C:\Users\simik\Downloads\ChristmasLights-master\firmware\notamesh4_gyver_v1.1\1main.ino:169:0:
colorwave.h:78:2: error: #endif without #if
 #endif
  ^~~~~
exit status 1
#endif without #if
```

**Comment by dronix27** [comment]
Так какое решение-то? Ставить предыдущую версию Ардуино Иде?

**Comment by AlexGyver** [comment]
"маркеры порядка байт" это что?

**Comment by simik-ru** [comment]
Эта пара невидимых байт в начале файла. https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%80%D0%BA%D0%B5%D1%80_%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B1%D0%B0%D0%B9%D1%82%D0%BE%D0%B2

**Comment by AlexGyver** [comment]
ну, писать в issue arduino, пусть фиксят

**Comment by simik-ru** [comment]
Лучше сотри этот символ в файлах, упомянутых в первом сообщении. Он все равно не нужен, а работать будет во всех версиях Ардуино ИДЕ.

**Comment by AlexGyver** [comment]
ну так покажи что стирать то, у меня никаких лишних символов не видно

**Comment by simik-ru** [comment]
Зависит от редактора. В гитхабовском редакторе этот символ показан как красная точка в самом начале файла.
В Ардуино ИДЕ он невидим, но видно, что подсветка синтаксиса на первой строчке не работает. стереть символ можно, достаточно поставить курсор в первую строку, нажать Home, потом Delete. Свиду ничего не удалится, но починится подсветка синтаксиса `#ifndef ...`

**Comment by AlexGyver** [comment]
ага, поправил. notepad++ никаких лишних символов не увидел

**Comment by Greykov** [comment]
Плохо подправил, ни везде. Если бы я не нашел эту ветку, то не решил бы проблему. Новый год на носу. Будьте внимательней к своим подписчикам, пожалуйста

**Comment by GyverLibs** [comment]
Где осталось? Я не в курсе что это и почему, и "быть внимательнее" тут не поможет

**Comment by Greykov** [comment]
Я недавно скачал с вашего сайта программу для гирлянды на адресной ленте, но она не работает , проблема описана несколькими постами выше. И даже ее решение там описано, но вы не исправили ошибку. Очень жаль ваших подписчиков.

**Comment by GyverLibs** [comment]
Если читать чуть внимательнее, то сообщением выше можно заметить фразу "ага, поправил"

**Comment by Greykov** [comment]
это было в 21 году, а я скачивал в декабре 23 года и проблема осталась, поэтому и весь сыр-бор

**Comment by AlexGyver** [comment]
@Greykov этой проблемы нет с 9 сентября 2021

**Comment by Greykov** [comment]
Странно, но я скачивал с вашего сайта эту прогу в декабре 2023 года и эта проблема у меня возникла.

**Comment by GyverLibs** [comment]
Я сегодня проверил все файлы на наличие лишних символов - их нет. Также скомпилил проект без ошибок

**Comment by Greykov** [comment]
Я искренне извиняюсь за беспокойство в предпраздничный день.Я только что скачал архив с вашего сайта , папка notamesh4_gyver, запустил компиляцию, первая строка не подсвечена. Ставлю курсор в первой строке на первую позицию и жму DEL, строка становится подсвеченной и далее все нормально
Программа Arduino 1.8.19 Что я делаю не правильно?

**Comment by AlexGyver** [comment]
использование старых версий - на свой страх и риск

**Comment by DimaMukhin84** [comment]
Откройте этот файлик Notepad++
Выделите, Преобразовать в UTF8 . Сохранить и все скомпилируется

**Comment by AlexGyver** [comment]
удалил старую версию, чтобы таких вопросов не было

**Comment by Greykov** [comment]
Благодарю!
